services:
    - docker
variables:
    SLIDEIO_VERSION: "0.5"
    LINUX_ARTIFACT_DIR: "linux"
    LINUX_PY_ARTIFACT_DIR: "linux-py"
    WINDOWS_ARTIFACT_DIR: "win"
    WINDOWS_PY_ARTIFACT_DIR: "win-py"
    PY_ARTIFACT_DIR: "python-wheels"
    DOC_ARTIFACT_DIR: "doc-dist"
stages:
    - build

python-manylinux:
    image: booritas/slideio-manylinux2010:latest
    stage: build
    script:
        - pwd
        - ls -l src/slideio/drivers/zvi
        - python3 ./install.py -a conan
        - cd src/pybind
        - bash ./install.sh
        - cd ../..
        - mkdir ./${LINUX_PY_ARTIFACT_DIR}
        - cp src/pybind/wheelhouse/* ./${LINUX_PY_ARTIFACT_DIR}
    artifacts:
        paths:
            - ./${LINUX_PY_ARTIFACT_DIR}
cpp-ubuntu:
    variables:
        WHL_PACKAGE: "slideio-${SLIDEIO_VERSION}.${CI_PIPELINE_IID}-cp38-cp38-linux_x86_64.whl"
    image: booritas/slideio-ubuntu-clang-9:latest
    stage: build
    script:
        - python -m pip install Sphinx
        - python ./install.py -a build
        - cd ${CI_PROJECT_DIR}
        - mkdir ./${LINUX_ARTIFACT_DIR}
        - mkdir ./${LINUX_ARTIFACT_DIR}/release
        - mkdir ./${LINUX_ARTIFACT_DIR}/debug
        - cp build/Linux/release/bin/* ./${LINUX_ARTIFACT_DIR}/release
        - cp build/Linux/debug/bin/* ./${LINUX_ARTIFACT_DIR}/debug
        - cd ./src/pybind
        - python setup.py sdist bdist_wheel
        - python -m pip install --ignore-installed ./dist/${WHL_PACKAGE}
        - cd ${CI_PROJECT_DIR}
        - cd doc
        - make html
        - cd ${CI_PROJECT_DIR}
        - mkdir ${DOC_ARTIFACT_DIR}
        - cp -r doc/build/html ${DOC_ARTIFACT_DIR}
    artifacts:
        paths:
            - ./${LINUX_ARTIFACT_DIR}
            - ./${DOC_ARTIFACT_DIR}
            