services:
    - docker
variables:
    SLIDEIO_VERSION: "0.3.0"
    LINUX_ARTIFACT_DIR: "linux"
    LINUX_PY_ARTIFACT_DIR: "linux-py"
    WINDOWS_ARTIFACT_DIR: "win"
    WINDOWS_PY_ARTIFACT_DIR: "win-py"
    PY_ARTIFACT_DIR: "python-wheels"
    DOC_ARTIFACT_DIR: "doc-dist"
stages:
    - build

python-manylinux:
    image: booritas/slideio-manylinux2010:latest
    stage: build
    script:
        - ls -l src/slideio/drivers/zvi
        - python3 ./install.py -a conan
        - cd src/pybind
        - bash ./install.sh
        - cd ../..
        - mkdir ./${LINUX_PY_ARTIFACT_DIR}
        - cp src/pybind/wheelhouse/* ./${LINUX_PY_ARTIFACT_DIR}
    artifacts:
        paths:
            - ./${LINUX_PY_ARTIFACT_DIR}