title: SlideIO
email: admin@slideio.com
description: >- # this means to ignore newlines until "baseurl:"
  Medical imaging library for python and c++.
url: "https://www.slideio.com" # the base hostname & protocol for your site, e.g. http://example.com
hydeout:
  repo: "https://github.com/Booritas/slideio"

author:
  name:           'Stanislav Melnikov'
  url:            https://www.linkedin.com/in/stanislav-melnikov/

# Build settings
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
