name: Mac arm pythons

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.13'
        architecture: 'arm64'

    - name: Display Python version
      run: python --version

    - name: Install tools
      run: |
        brew install pyenv openssl readline sqlite3 xz zlib tree

    - name: Install pythons
      run: |
        pyenv install --list
        pyenv install 3.11.9
        pyenv install 3.12.4
    - name: Create python package deployment list
      run: |
        python3 ./src/py-bind/install_py_dists.py ~/.pyenv/versions ./py.txt
        cat ./py.txt
