name: Build slideio python packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CONAN_REVISIONS_ENABLED: 1
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: create python packages
      #working-directory: .\src\pybind
      run: echo "$GITHUB_WORKSPACE\conan-recepies\python.txt"

    - name: display file
      #working-directory: .\src\pybind
      run: cat "$GITHUB_WORKSPACE\conan-recepies\python.txt"

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add slideio conan remote
      run: conan remote add slideio ${{ secrets.CONAN_REMOTE }}
      
    - name: Login to slideio conan remote
      run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r slideio ${{ secrets.CONAN_USER }}

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

      
    - name: chekout conan recipes
      run: git clone 'https://gitlab.com/bioslide/conan-recipes.git' conan-recipes

    - name: install python distributions
      working-directory: ./conan-recipes
      run: powershell ./install.ps1


    # - name: Install conan dependencies
    #   run: python install.py -a conan

    # - name: compile
    #   run: |
    #     cd src/pybind
    #     powershell install.ps1
