name: Conan build and upload dependencies

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Display Python version
      run: python --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add slideio conan remote
      run: conan remote add slideio ${{ secrets.CONAN_REMOTE }}
      
    - name: Login to slideio conan remote
      run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r slideio ${{ secrets.CONAN_USER }}

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install conan dependencies
      run: python install.py -a conan

    - run: conan upload "ndpi-libtiff/4.3.0@slideio/stable" -r slideio --all
    - run: conan upload "opencv/4.1.1@slideio/stable" -r slideio --all
    - run: conan upload "pole/1.0.1@slideio/stable" -r slideio --all