name: Mac conan dependencies

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Display Python version
      run: python --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.63.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add digital ocean conan remote
      run: |
        conan remote add digitalo http://167.172.176.224
        conan user -p ${{ secrets.CONAN_DO_PASSWORD }} -r digitalo ${{ secrets.CONAN_DO_USER }}

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install conan dependencies
      run: python install.py -a conan -c release

    - name: Upload packages to digiatal ocean
      run: conan upload "*" -r digitalo --all -c      
      