name: manylinux_2_28_x86_64 docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Dockerhub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      working-directory: ./docker/manylinux_2_28_x86_64
      run: docker build --build-arg CONAN_LOGIN_USERNAME=${{ secrets.CONAN_USER }} --build-arg CONAN_PASSWORD=${{ secrets.CONAN_PASSWORD }} --build-arg CONAN_SERVER_URL=${{ secrets.CONAN_URL }} -t slideio-manylinux_2_28_x86_64:2.7.1 .
  
    - name: Tag Docker image
      run: docker tag slideio-manylinux_2_28_x86_64:2.7.1 booritas/slideio-manylinux_2_28_x86_64:2.7.1
  
    - name: Push Docker image
      run: docker push booritas/slideio-manylinux_2_28_x86_64:2.7.1
  
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Tag Docker image
      run: docker tag slideio-manylinux_2_28_x86_64:2.7.1 ghcr.io/booritas/slideio/slideio-manylinux_2_28_x86_64:2.7.1

    - name: Push Docker image
      run: docker push ghcr.io/booritas/slideio/slideio-manylinux_2_28_x86_64:2.7.1
