name: Build slideio python packages

on:
  create:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: booritas/slideio-manylinux2014:v0.62
      env:
        CONAN_REVISIONS_ENABLED: 1

    steps:

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add slideio conan remote
      run: conan remote add slideio ${{ secrets.CONAN_REMOTE }}
      
    - name: Login to slideio conan remote
      run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r slideio ${{ secrets.CONAN_USER }}

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
  
    - name: compile libxml2
      run: conan install -pr ./conan/Linux/multilinux/linux_release -b libxml2  libxml2/2.9.10@_/_

    - name: compile sqlite3
      run: conan install -pr ./conan/Linux/multilinux/linux_release -b sqlite3  sqlite3/3.36.0@_/_


    - name: Install conan dependencies
      run: python3 install.py -a conan -c release
      
    - name: find references
      run: bash ./search.sh

    - name: build python packages
      working-directory: ./src/pybind
      run: bash ./install.sh

    - name: Archive python packagess
      uses: actions/upload-artifact@v2
      with:
        name: python-dist
        path: |
          ./src/pybind/wheelhouse