name: Linux slideio build

on: [workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: booritas/slideio-manylinux2014:v2.1.0
      env:
        CONAN_REVISIONS_ENABLED: 1

    steps:
    - name: Install conan
      run: python3 -m pip install -U conan==1.64.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
      
    - name: Add digital ocean conan remote
      run: |
        conan remote add digitalo http://167.172.176.224
        conan user -p ${{ secrets.CONAN_DO_PASSWORD }} -r digitalo ${{ secrets.CONAN_DO_USER }}      

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
  
    - name: Install conan dependencies
      run: python3 install.py -a conan -c release
      
    - name: build python packages
      working-directory: ./src/py-bind
      run: bash ./build_slideio_dists_linux.sh

    - name: Archive python packagess
      uses: actions/upload-artifact@v2
      with:
        name: python-dist
        path: |
          ./src/py-bind/wheelhouse
