name: Macos build slideio wheels

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-12, macos-14]
        os: [macos-14]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v3

    - name: Display Python version
      run: python --version

    - name: Install Conan
      run: |
         eval "$(conda shell.bash hook)"
         conda create -n conan  -y python==3.10
         conda activate conan
         python -m pip install conan==1.64.0
         conan remote add digitalo http://167.172.176.224
         conan user -p ${{ secrets.CONAN_DO_PASSWORD }} -r digitalo ${{ secrets.CONAN_DO_USER }}
         python install.py -a conan  -c release
         conan upload "*" -r digitalo --all -c      

    - name: build Windows python packages
      if: runner.os == 'Windows'
      working-directory: ./src/py-bind
      run: powershell ./build-wheels.sh

    - name: build Macos python packages
      if: runner.os == 'macOS'
      working-directory: ./src/py-bind
      run: bash ./build-wheels.sh

    - name: Archive python packagess
      uses: actions/upload-artifact@v4
      with:
        name: python-dist
        path: |
          ./src/py-bind/dist