name: Windows build slideio wheels

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Display Python version
      run: python --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.65.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add digital ocean conan remote
      run: |
        conan remote add digitalo http://167.172.176.224
        conan user -p ${{ secrets.CONAN_DO_PASSWORD }} -r digitalo ${{ secrets.CONAN_DO_USER }}

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: chekout conan recipes
      run: git clone 'https://gitlab.com/bioslide/conan-recipes.git' conan-recipes

    - name: install python distributions
      working-directory: ./conan-recipes
      run: python deploy-python-dists.py

    - name: Install conan dependencies
      run: python install.py -a conan  -c release

    - name: Upload conan packages to conan server
      run: conan upload "*" -r digitalo --all -c
      continue-on-error: true

    - name: build python packages
      shell: pwsh
      working-directory: ./src/py-bind
      run: powershell .\build-wheels-win.ps1

    - name: Archive python packagess
      uses: actions/upload-artifact@v4
      with:
        name: python-dist
        path: |
          ./src/py-bind/dist