name: Windows build slideio wheels

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:

    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Display Python version
      run: python --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.10.1

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    # - name: Add digital ocean conan remote
    #   run: |
    #     conan remote add digitalo http://167.172.176.224
    #     conan user -p ${{ secrets.CONAN_DO_PASSWORD }} -r digitalo ${{ secrets.CONAN_DO_USER }}

    - name: checkout slideio
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        ref: v2.7.0
        path: slideio 

    - name: chekout conan recipes
      uses: actions/checkout@v2
      with:
        repository: Booritas/conan-center-index
        ref: v2.7.0
        path: conan-center-index

    - name: build custom conan recepies
      working-directory: ./slideio
      env:
        SLIDEIO_HOME: $GITHUB_WORKSPACE/slideio
        CONAN_INDEX_HOME: $GITHUB_WORKSPACE/conan-center-index
      shell: pwsh
      run: ./conan.ps1

    - name: Install all conan dependencies
      working-directory: ./slideio
      run: python install.py -a conan  -c release

    # - name: Upload conan packages to conan server
    #   run: conan upload "*" -r digitalo --all -c
    #   continue-on-error: true

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: ""

    - name: build python packages
      shell: pwsh
      working-directory: ./slideio/src/py-bind
      run: powershell .\build-wheels-win.ps1

    - name: Archive python packagess
      uses: actions/upload-artifact@v4
      with:
        name: python-dist
        path: |
          ./src/py-bind/dist